### ISSUE TITLE
Dimension Change

### ISSUE THREAD

**Issue by neziw** [Dimatert9/BungeeCord#108]

**Comment by Leymooo** [comment]
Добавлю когда будет возможность

**Comment by neziw** [comment]
> Добавлю когда будет возможность

Я хотел сделать это сам. Однако я не понимаю, где взять байты, которые находятся в классе JoinGame

**Comment by neziw** [comment]
@Leymooo и что вы думаете об изменении размерности в конфигурации или загрузки файла .schematic в будущем?
