### ISSUE TITLE
(Geyser 1.19 bug)

### ISSUE THREAD

**Issue by xism4** [Dimatert9/BungeeCord#123]
For some reason commands are not recognised, and trougth some debugs i think that the problem is Dimension class. 
- > The issue here is that when Bedrock player joins and asks for captcha, just kicks it for invalid captcha/max time because is beeing ignored for some reason.

**Comment by NoJokeFNA** [comment]
Isn't there a "SKIP_GEYSER" option in the config which ignores captchas?

**Comment by xism4** [comment]
> Isn't there a "SKIP_GEYSER" option in the config which ignores captchas?

Well, does not properly ignore it because some times still asking captcha, it could be an easier way to fix this issue yeah.

**Comment by xism4** [comment]
fixed for myself, thanks tho.

**Comment by NovaPixell** [comment]
> 

Hi! How did you fixed this?
