### ISSUE TITLE
Выдает ошибку после обновления на java 17

### ISSUE THREAD

**Issue by 2006lev-Web** [Dimatert9/BungeeCord#125]
![image](https://user-images.githubusercontent.com/64630503/180146934-4773f5ee-e943-4b3c-a73c-37b096e54d47.png)

**Comment by xism4** [comment]
> ![image](https://user-images.githubusercontent.com/64630503/180146934-4773f5ee-e943-4b3c-a73c-37b096e54d47.png)

Seems that you are using 1.18 version, not lastest upgrade.

**Comment by 2006lev-Web** [comment]
> 

and where can I download the latest version, I just can't find it

**Comment by loperd** [comment]
@2006lev-Web really? Try this link https://www.oracle.com/java/technologies/javase/jdk18-archive-downloads.html

**Comment by 2006lev-Web** [comment]
![image](https://user-images.githubusercontent.com/64630503/180647537-60843aac-4079-456d-b0af-892bacc169cc.png)
After updating to java 18, the error did not disappear

**Comment by Leymooo** [comment]
#90
