### ISSUE TITLE
Ошибка при вторичном запуске в докере

### ISSUE THREAD

**Issue by leolnid** [Dimatert9/BungeeCord#97]
Использую: https://github.com/itzg/docker-bungeecord
Если брать стандартную банжу или waterfall - все ок

---
Логи при запуске
20:47:12 [SEVERE] Exception in thread "main"
20:47:12 [SEVERE] java.lang.reflect.InaccessibleObjectException: Unable to make private native java.lang.reflect.Field[]  java.lang.Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @5274766b
20:47:12 [SEVERE]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
20:47:12 [SEVERE]     at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
20:47:12 [SEVERE]     at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
20:47:12 [SEVERE]     at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
20:47:12 [SEVERE]     at ru.leymooo.botfilter.config.Config.setAccessible(Config.java:371)
20:47:12 [SEVERE]     at ru.leymooo.botfilter.config.Config.getField(Config.java:258)
20:47:12 [SEVERE]     at ru.leymooo.botfilter.config.Config.set(Config.java:54)
20:47:12 [SEVERE]     at ru.leymooo.botfilter.config.Config.set(Config.java:114)
20:47:12 [SEVERE]     at ru.leymooo.botfilter.config.Config.load(Config.java:99)
20:47:12 [SEVERE]     at ru.leymooo.botfilter.config.Settings.reload(Settings.java:60)
20:47:12 [SEVERE]     at ru.leymooo.botfilter.BotFilter.<init>(BotFilter.java:74)
20:47:12 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:282)
20:47:12 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49)
20:47:12 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

---
Конфиг для docker-compose
version: "3.7"

services:
  proxy:
    image: itzg/bungeecord
    environment:
      TYPE: CUSTOM
      BUNGEE_JAR_FILE: server-3.8.8.1.jar
    restart: unless-stopped
    ports:
      - "25565:25577"
    volumes:
      - "./proxy:/server"

**Comment by Leymooo** [comment]
https://github.com/Leymooo/BungeeCord/issues/90
